"on":
  push:
    branches:
    - master
name: Deploy to mirror
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply
      env:
        PORTER_CLUSTER: "1444"
        PORTER_DEPLOYMENT_TARGET_ID: f18f2a35-f6b5-41b3-a6f3-4bdc484acbdd
        PORTER_HOST: https://cloud.porter.run
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "1531"
        PORTER_REPO_NAME: ${{ github.event.repository.name }}
        PORTER_STACK_NAME: mirror
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1531_1444 }}
